# statsserver.url: http://stats-server:9090 # если запускаем в контейнере
statsserver.url: http://localhost:9090   # если запускаем на хосте

server:
  port: 8080

spring:
  application:
    name: ewm-service
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    # url: jdbc:postgresql://postgres-ewm-main-db:5432/ewmdb # Вариант 1: Использовать имя контейнера и внутренний порт (если запускаем в контейнере)
    url: jdbc:postgresql://localhost:5434/ewmdb # Вариант 2: Использовать localhost и внешний порт (если запускаем на хосте)
    username: dbuser
    password: 123456
