services:
  

  stats-db:
    image: postgres:16.1
    container_name: postgres-ewm-stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=statsdb
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=123456
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -u $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10


  stats-server:
    ports:
      - "9090:9090"
    build: stats-server
    image: stats-server
    container_name: stats-server
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsdb
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=123456


  ewm-service:
    ports:
      - "8080:8080"
    build: ewm-service
    image: ewm-service
    container_name: ewm-service
    depends_on:
      - stats-server
