server:
  port: 9090

spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:stats
    driver-class-name: org.h2.Driver
    username: stat
    password: stat
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect